image: mischief/docker-golang
env:
  - GOPATH=/var/cache/drone
script:
  - go build
  - sleep 15
  - go test -v
services:
  - redis
notify:
  email:
    recipients:
      - brad@drone.io
      - burke@drone.io
